# Generated by Django 5.2.7 on 2025-10-26 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitioTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Termales Santa Rosa de Cabal', max_length=200)),
                ('descripcion_corta', models.TextField(help_text='Descripción breve para tarjeta', max_length=300)),
                ('descripcion_completa', models.TextField(help_text='Descripción detallada')),
                ('imagen_principal', models.ImageField(help_text='Imagen para lista', upload_to='sitios_turisticos/')),
                ('imagen_detalle', models.ImageField(blank=True, help_text='Imagen grande para página de detalle', null=True, upload_to='sitios_turisticos/')),
                ('ubicacion', models.CharField(help_text='Ej: A 15 minutos en carro desde Turquesa Hostel', max_length=300)),
                ('coordenadas_lat', models.DecimalField(blank=True, decimal_places=6, help_text='Latitud para Google Maps', max_digits=9, null=True)),
                ('coordenadas_lng', models.DecimalField(blank=True, decimal_places=6, help_text='Longitud para Google Maps', max_digits=9, null=True)),
                ('actividades', models.TextField(help_text='Ej: Baños termales, caminatas cortas, fotografía')),
                ('tips', models.TextField(help_text='Ej: Lleva traje de baño, sandalias y una muda extra de ropa')),
                ('orden', models.IntegerField(default=0, help_text='Orden de aparición (menor número = primero)')),
                ('activo', models.BooleanField(default=True, help_text='Mostrar en la web')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sitio Turístico',
                'verbose_name_plural': 'Sitios Turísticos',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
