# Generated by Django 5.2.7 on 2025-10-27 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_sitioturistico'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformacionHostal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Turquesa Hostal', max_length=200)),
                ('eslogan', models.CharField(help_text=' UN ESPACIO ECOLÓGICO Y FAMILIAR', max_length=300)),
                ('descripcion_corta', models.TextField(help_text='Descripción breve para la home')),
                ('descripcion_completa', models.TextField(help_text='Descripción detallada')),
                ('direccion', models.CharField(max_length=300)),
                ('ciudad', models.CharField(default='Santa Rosa de Cabal', max_length=100)),
                ('departamento', models.CharField(default='Risaralda', max_length=100)),
                ('pais', models.CharField(default='Colombia', max_length=100)),
                ('coordenadas_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('coordenadas_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(help_text='Número de WhatsApp Business', max_length=20)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('checkin_desde', models.TimeField(default='15:00', help_text='Check-in desde las')),
                ('checkout_hasta', models.TimeField(default='11:00', help_text='Check-out hasta las')),
                ('sala_comun', models.BooleanField(default=True)),
                ('sala_comun_descripcion', models.CharField(default='Un espacio para descansar y compartir', max_length=200)),
                ('cocina_compartida', models.BooleanField(default=True)),
                ('cocina_compartida_descripcion', models.CharField(default='Equipada para que prepares tus comidas', max_length=200)),
                ('banos_compartidos', models.BooleanField(default=True)),
                ('banos_compartidos_descripcion', models.CharField(default='Cómodos y limpios para todos los huéspedes', max_length=200)),
                ('hogar_familiar', models.BooleanField(default=True)),
                ('hogar_familiar_descripcion', models.CharField(default='La calidez de sentirse como en casa, en un entorno acogedor', max_length=200)),
                ('ambiente_sano', models.BooleanField(default=True)),
                ('ambiente_sano_descripcion', models.CharField(default='Un espacio libre de humo y excesos, ideal para descansar', max_length=200)),
                ('entorno_ecologico', models.BooleanField(default=True)),
                ('entorno_ecologico_descripcion', models.CharField(default='Un lugar limpio y consciente para disfrutar con tranquilidad', max_length=200)),
                ('politicas_cancelacion', models.TextField(blank=True, help_text='Políticas de cancelación')),
                ('politicas_mascotas', models.TextField(blank=True, help_text='Políticas sobre mascotas')),
                ('politicas_fumar', models.TextField(blank=True, help_text='Políticas sobre fumar')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='hostal/')),
                ('imagen_principal', models.ImageField(blank=True, help_text='Imagen para la home', null=True, upload_to='hostal/')),
                ('copyright_text', models.CharField(default='© 2025 Turquesa hostal', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Información del Hostal',
                'verbose_name_plural': 'Información del Hostal',
            },
        ),
    ]
