# Generated by Django 5.2.8 on 2025-11-11 20:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_informacionhostal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='informacionhostal',
            name='imagen_principal',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen_principal'),
        ),
        migrations.AlterField(
            model_name='informacionhostal',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='sitioturistico',
            name='imagen_detalle',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen_detalle'),
        ),
        migrations.AlterField(
            model_name='sitioturistico',
            name='imagen_principal',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagen_principal'),
        ),
    ]
