# Generated by Django 5.2.8 on 2025-11-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_alter_habitacion_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='tipo',
            field=models.CharField(choices=[('doble', 'Habitación Doble (2 personas)'), ('doble_sencilla', 'Habitación Doble Sencilla (2 personas)'), ('triple', 'Habitación Triple (3 personas)'), ('familiar', 'Habitación Familiar (5 personas)'), ('familiar_grande', 'Habitación Familiar Grande (5 personas)'), ('suite', 'Habitación Suite (5 personas)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='informacionhostal',
            name='eslogan',
            field=models.CharField(help_text='UN ESPACIO ECOLÓGICO Y FAMILIAR', max_length=300),
        ),
    ]
